add meta-deepbdc and stl-deepbdc
RL-VIG/LibFewShot pull request #67
Opened 2023-02-09 17:43 UTC by stu-yue

本次PR为添加`meta-deepbdc(pretrain\metatrain)`和`stl-deepbdc(pretrain\distill)`方法，除了新添加的py及yaml文件及修改相应`__init__.py`文件外，还对以下文件做了修改：

+ `core/data/dataloader.py`：为保证`deepbdc`在miniImageNet上复现效果更好，故在`dataloader.py`文件中添加了`deepbdc`原文中对应的transformer方法。

+ `core/trainer.py`：

  + 第一个是注释掉`nn.utils.clip_grad_norm_`，经过实验对比，开启clip grad norm后模型更新梯度变小，下降速度变慢，且收敛不到原文精度(比原文精度低2-3%)；

  + 第二个是对`init_optim`作了简单修改，使得可以在模型训练时对指定参数设置学习率(之前是按模型的module大小设置，由于`deepbdc`中需要对某个`nn.Parameter`设置，故修改于此)：

    ```python
            params_dict_list = []
            if "other" in config["optimizer"] and config["optimizer"]["other"] is not None:
                for key, value in config["optimizer"]["other"].items():
                    # FIXME: Set the learning rate for the model specified parameter, 
                    # including nn.Module and nn.Parameter
                    # Original:
                    # Pre-modified:
                    # if self.distribute:
                    #     sub_model = getattr(self.model.module, key)
                    # else:
                    #     sub_model = getattr(self.model, key)
    
                    # Modified:
                    if self.distribute:
                        sub_model = eval("self.model.module." + key)
                    else:
                        sub_model = eval("self.model." + key)
                    if isinstance(sub_model, nn.Module):
                        sub_model_params_list = list(sub_model.parameters())
                    elif isinstance(sub_model, nn.Parameter):
                        sub_model_params_list = [sub_model]
                    else:
                        raise Exception("Unrecognized type in optimizer.other")
    
                    params_idx.extend(list(map(id, sub_model_params_list)))
                    if value is None:
                        for p in sub_model_params_list:
                            p.requires_grad = False
                    else:
                        param_dict = {"params": sub_model_params_list}
                        if isinstance(value, float):
                            param_dict.update({"lr": value})
                        elif isinstance(value, dict):
    ```

    yaml中可对optimizer如下设置：

    ```yaml
    optimizer:
      kwargs:
        lr: 0.05
        momentum: 0.9
        nesterov: true
        weight_decay: 0.0005
      name: SGD
      other: 
        emb_func.bdc_pool.temperature: 0.001	# 指定Parameter
    ```

最后，训练模型([网盘地址](https://pan.baidu.com/s/1pWEkrz-OAvunuL7q2j-u0A?pwd=jruw ))在miniImageNet的精度如下：

+ 原文结果：

  |              |  ResNet-12   |  ResNet-12   |
  | :----------: | :----------: | :----------: |
  |    Method    | 5-way-1-shot | 5-way-5-shot |
  | Meta DeepBDC |  67.34±0.43  |  84.46±0.28  |
  | STL  DeepBDC |  67.83±0.43  |  85.45±0.29  |

+ 复现结果：

  |              |    ResNet-12    |    ResNet-12    |
  | :----------: | :-------------: | :-------------: |
  |    Method    |  5-way-1-shot   |  5-way-5-shot   |
  | Meta DeepBDC | 66.304(h:0.198) | 83.935(h:0.287) |
  | STL  DeepBDC | 66.170(h:0.192) | 84.268(h:0.294) |

  > ```python
  > # run_test.py
  > VAR_DICT = {
  >     "test_epoch": 5,
  >     "device_ids": "2",
  >     "n_gpu": 1,
  >     "test_episode": 2000,
  >     "test_query": 15,
  >     "test_shot": 1,
  >     "episode_size": 1,
  > }
  > ```

2023-02-14 08:26 UTC, wZuck commented on core/data/dataloader.py
> +            if (
这部分原来写了固定的增广方法是希望有一个较为统一的增广，排除增广trick带来的干扰，确实在添加新方法时会有一些不便。我的想法是可以在这里进行大改，把`trfms_list.append(transforms.ToTensor())`之前的代码都合并到`get_augment_method `函数中，如果没有`augment_method`这个键或者值为`NormalAug`，则依然使用这一套增广，否则提供一组新的增广。

2023-02-14 08:33 UTC, wZuck requested changes
增广部分方便按照说明修改吗，这样更通用一些

2023-02-15 07:18 UTC, stu-yue commented on core/data/dataloader.py
> +            if (
好的👌

2023-02-19 05:34 UTC, wZuck approved these changes
看起来非常好👍

2023-02-19 05:34 UTC, merged