Add s2m2
RL-VIG/LibFewShot pull request #70
Opened 2023-02-22 02:49 UTC by VincenDen

重新PR

2023-02-22 13:07 UTC, wZuck requested changes
可以对这几个comment做一些调整吗？

2023-02-22 13:07 UTC, wZuck commented on core/data/dataloader.py
> +    if(config["augment_method"] == "S2M2Augment"):
这里不如模仿get_augment_method再做一下包装？单独的MEAN STD出现在这里看起来有一些突兀。

2023-02-22 13:07 UTC, wZuck commented on core/model/backbone/resnet_18_mm.py
> +# -*- coding: utf-8 -*-
这个Backbone和已经存在的ResNet18有能够抽象的部分吗，如果可以合在一个文件里最好，不行的话就这样保留吧。

2023-02-22 13:07 UTC, wZuck commented on core/model/finetuning/s2m2.py
> +def crit(output, features, target):
loss函数可以放到方法类初始化里，参考其他方法。

2023-02-22 13:07 UTC, wZuck commented on core/model/finetuning/s2m2.py
> +        #rotations=True
https://github.com/RL-VIG/LibFewShot/blob/8e8532579a9a6c44165e2553f376f165ab1a9b23/core/model/finetuning/skd_model.py#L199 是否可以复用？

2023-02-22 13:07 UTC, wZuck commented on core/model/finetuning/s2m2.py
> +        target_ =Variable(torch.stack(target_,0)).to(self.device)
Variable已经被弃用，去掉也可以。

2023-02-26 07:31 UTC, VincenDen commented on core/data/collates/contrib/__init__.py
> +    if "augment_method" not in config or config["augment_method"] == "NormalAug":
对mean std获取进行了包装

2023-02-26 07:32 UTC, VincenDen commented on core/model/backbone/resnet_18.py
> +    def forward(self, x,index_mixup=None, lam=-1):
合并到原有backbone中

2023-02-26 07:34 UTC, VincenDen commented on core/model/finetuning/s2m2.py
> +    def  rot_image_generation(self, image, target):
s2m2的rotation只选取了bacth的四分之一而不是全部batch进行选择，不好复用，但是进行类似的函数封装

2023-02-26 07:35 UTC, VincenDen commented on core/model/finetuning/s2m2.py
> +
varible变量语法已删除

2023-02-26 07:35 UTC, VincenDen commented on core/model/finetuning/s2m2.py
> +        self.loss_func = nn.CrossEntropyLoss()
loss函数已放在类初始化中

2023-03-01 08:01 UTC, wZuck approved these changes

2023-03-01 08:01 UTC, merged